#version 430 
layout (local_size_x = 4, local_size_y = 4, local_size_z = 1) in;
layout(binding = 0, r32f) uniform image2D ColorImg;
layout(std430, binding = 1) buffer OutputBuffer{float c[];};



uniform int RowLength;



void main()
{
	uint x = gl_GlobalInvocationID.x;
	uint y = gl_GlobalInvocationID.y;
	uint index = x  + y * RowLength;
	
	c[index] = imageLoad(ColorImg, ivec2(x,y)).r;
	//c[index] = index;
}