#version 430 
layout (local_size_x = 1, local_size_y = 32, local_size_z = 1) in;

layout(binding = 0, r32f) uniform image2D ColorImg;
layout(std430, binding = 1) buffer InputBuffer{float b[];};
layout(std430, binding = 2) buffer OutputBuffer{float c[];};

uniform int RowLength;

void main()
{
	uint y = gl_GlobalInvocationID.y;
	float sum = 0.0;
	for(int x = 0; x < RowLength; x++)
	{
		sum += imageLoad(ColorImg, ivec2(x,y)).r * b[x];
	}

	c[y] = sum;
}