#version 430

layout(local_size_x = 16, local_size_y = 16) in;
//layout( binding = 0, rgba32f) uniform image2D ColorImg;
layout( binding = 0, rgba8) uniform image2D ColorImg;

void main() 
{
  ivec2 xy = ivec2(gl_GlobalInvocationID.xy);
  // get pixel from texture
  vec4 pixelColor = imageLoad(ColorImg, xy);
  // modify alpha-channel
  pixelColor.a *= 0.75;
  // set pixel in texture
  imageStore(ColorImg, xy, pixelColor);
}
